import { Barber, Service, Product, Promotion, Appointment, Order } from './types';

export const BARBERS: Barber[] = [
  {
    id: 'b1',
    firstName: 'Marcus',
    lastName: 'DUMONT',
    avatar: 'https://i.pravatar.cc/150?img=11',
    specialty: 'Dégradés & Designs',
    rating: 4.9,
    reviewCount: 234,
    available: true,
    schedule: {},
  },
  {
    id: 'b2',
    firstName: 'Jordan',
    lastName: 'VINCENT',
    avatar: 'https://i.pravatar.cc/150?img=12',
    specialty: 'Coupes classiques & Barbe',
    rating: 4.8,
    reviewCount: 189,
    available: true,
    schedule: {},
  },
  {
    id: 'b3',
    firstName: 'Kevin',
    lastName: 'PIERRE',
    avatar: 'https://i.pravatar.cc/150?img=13',
    specialty: 'Rasage & Soins',
    rating: 4.7,
    reviewCount: 156,
    available: false,
    schedule: {},
  },
  {
    id: 'b4',
    firstName: 'Théo',
    lastName: 'BAMANA',
    avatar: 'https://i.pravatar.cc/150?img=14',
    specialty: 'Art capillaire & Tresses',
    rating: 4.9,
    reviewCount: 312,
    available: true,
    schedule: {},
  },
];

export const SERVICES: Service[] = [
  {
    id: 's1',
    name: 'Coupe',
    description: 'Coupe précise adaptée à votre style, finitions soignées',
    price: 20,
    duration: 30,
    icon: 'cut',
    category: 'coupe',
  },
  {
    id: 's2',
    name: 'Coupe + Barbe',
    description: 'Coupe complète avec taille et dessin de la barbe',
    price: 30,
    duration: 45,
    icon: 'cut',
    category: 'pack',
  },
  {
    id: 's3',
    name: 'Dégradé',
    description: 'Dégradé américain ou bas, rendu impeccable',
    price: 25,
    duration: 40,
    icon: 'cut',
    category: 'coupe',
  },
  {
    id: 's4',
    name: 'Rasage',
    description: 'Rasage traditionnel au rasoir droit, avec serviette chaude',
    price: 20,
    duration: 30,
    icon: 'cut',
    category: 'barbe',
  },
  {
    id: 's5',
    name: 'Barbe seule',
    description: 'Taille, dessin et soin de la barbe',
    price: 15,
    duration: 20,
    icon: 'cut',
    category: 'barbe',
  },
  {
    id: 's6',
    name: 'Soin du cuir chevelu',
    description: 'Traitement nourrissant + massage relaxant',
    price: 25,
    duration: 30,
    icon: 'cut',
    category: 'soin',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Pomade Gold Edition',
    description: 'Tenue forte brillance naturelle, parfum premium',
    price: 18,
    image: 'https://images.unsplash.com/photo-1626808641505-a8d29a6c3a0e?w=400',
    category: 'styling',
    stock: 45,
    brand: "BARB'OR",
    rating: 4.8,
    reviewCount: 89,
  },
  {
    id: 'p2',
    name: 'Huile de Barbe Premium',
    description: 'Mélange d\'huiles naturelles pour une barbe soyeuse',
    price: 22,
    image: 'https://images.unsplash.com/photo-1626808641505-a8d29a6c3a0e?w=400',
    category: 'soins',
    stock: 30,
    brand: "BARB'OR",
    rating: 4.9,
    reviewCount: 124,
  },
  {
    id: 'p3',
    name: 'Shampoing Homme Noir',
    description: 'Shampoing purifiant au charbon actif',
    price: 14,
    image: 'https://images.unsplash.com/photo-1626808641505-a8d29a6c3a0e?w=400',
    category: 'soins',
    stock: 60,
    brand: "BARB'OR",
    rating: 4.6,
    reviewCount: 67,
  },
  {
    id: 'p4',
    name: 'Peigne Pro Corne Noire',
    description: 'Peigne en corne naturelle anti-statique',
    price: 12,
    image: 'https://images.unsplash.com/photo-1626808641505-a8d29a6c3a0e?w=400',
    category: 'accessoires',
    stock: 25,
    brand: "PRO LINE",
    rating: 4.7,
    reviewCount: 43,
  },
  {
    id: 'p5',
    name: 'Baume Après-Rasage Gold',
    description: 'Baume apaisant avec extraits d\'or et aloe vera',
    price: 19,
    image: 'https://images.unsplash.com/photo-1626808641505-a8d29a6c3a0e?w=400',
    category: 'soins',
    stock: 38,
    brand: "BARB'OR",
    rating: 4.8,
    reviewCount: 92,
  },
  {
    id: 'p6',
    name: 'Cape Barber Gold Edition',
    description: 'Cape de coupe waterproof logo BARB\'OR',
    price: 35,
    image: 'https://images.unsplash.com/photo-1626808641505-a8d29a6c3a0e?w=400',
    category: 'accessoires',
    stock: 15,
    brand: "BARB'OR",
    rating: 4.9,
    reviewCount: 28,
  },
  {
    id: 'p7',
    name: 'Cire Mate Premium',
    description: 'Finition mate longue tenue, look naturel',
    price: 16,
    image: 'https://images.unsplash.com/photo-1626808641505-a8d29a6c3a0e?w=400',
    category: 'styling',
    stock: 52,
    brand: "BARB'OR",
    rating: 4.7,
    reviewCount: 73,
  },
  {
    id: 'p8',
    name: 'Rasoir Droit Professionnel',
    description: 'Rasoir en acier inoxydable, manche en bois d\'ébène',
    price: 65,
    image: 'https://images.unsplash.com/photo-1626808641505-a8d29a6c3a0e?w=400',
    category: 'accessoires',
    stock: 10,
    brand: "MASTER BLADE",
    rating: 4.9,
    reviewCount: 56,
  },
];

export const PROMOTIONS: Promotion[] = [
  {
    id: 'promo1',
    title: '🏆 Pack VIP Printemps',
    description: 'Coupe + Barbe + Soin du cuir chevelu à prix réduit',
    discount: 20,
    discountType: 'percent',
    validUntil: '2024-04-30',
    code: 'VIP20',
  },
  {
    id: 'promo2',
    title: '🚗 1er BARB\'DRIVER offert',
    description: 'Frais de déplacement offerts pour votre première commande à domicile',
    discount: 15,
    discountType: 'fixed',
    validUntil: '2024-05-31',
    code: 'DRIVER1',
  },
  {
    id: 'promo3',
    title: '💛 Fidélité Gold',
    description: '10ème coupe offerte pour les membres Gold',
    discount: 100,
    discountType: 'percent',
    validUntil: '2024-12-31',
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt1',
    clientId: 'u1',
    barberId: 'b1',
    barber: BARBERS[0],
    serviceId: 's2',
    service: SERVICES[1],
    date: '2024-04-10',
    time: '14:00',
    status: 'confirmed',
    depositPaid: true,
    depositAmount: 10,
    totalAmount: 30,
    createdAt: '2024-04-05T10:30:00Z',
  },
  {
    id: 'apt2',
    clientId: 'u1',
    barberId: 'b3',
    barber: BARBERS[2],
    serviceId: 's4',
    service: SERVICES[3],
    date: '2024-03-22',
    time: '10:30',
    status: 'completed',
    depositPaid: true,
    depositAmount: 10,
    totalAmount: 20,
    createdAt: '2024-03-18T09:00:00Z',
  },
];

export const TIME_SLOTS = [
  '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
  '12:00', '12:30', '14:00', '14:30', '15:00', '15:30',
  '16:00', '16:30', '17:00', '17:30', '18:00', '18:30',
];

export const BARB_DRIVER_ZONE = {
  centerLat: 4.9224,
  centerLng: -52.3135,
  radiusKm: 20,
  baseFee: 10,
  perKmFee: 1.5,
};
